import "./globals.css";


export const metadata = {
  title: {
    default: "Khana Khazana 04",
    template: "%s | Khana Khazana 04",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
